@startuml 5.1.1
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Admin" as AD
participant "Frontend" as FE <<component>>
participant "DM Backend" as BE <<component>>



activate AD
AD -> FE: access page
activate FE
FE -> BE: getStaffEditForm()
activate BE
BE --> FE: form
deactivate BE
FE --> AD : staff data edit input
deactivate FE
AD -> FE : edit info of Staff Profile
activate FE
FE -> BE : Update(string id, StaffDto dto)
activate BE
BE --> FE: success
deactivate BE
FE --> AD : success of operation and edited data
deactivate FE
deactivate AD


@enduml