@startuml 5.1.9
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Controller" as CTRL <<component>>
participant "Service" as SERV <<component>>
participant "Domain" as DOM <<component>>
participant "Repository" as REPO <<component>>
participant "MySql DB" as BDD <<component>>


-> CTRL: Submit Patient Put Request
activate CTRL

CTRL -> SERV: Call UpdateAsync method
activate SERV

SERV -> REPO: Get Patient through DTO Email
activate REPO

REPO --> SERV: Return Patient
deactivate REPO
'TODO: Fazer algo referente à informação sensivel (?)
SERV -> DOM: Update Patient with PatientDTO Info
activate DOM

DOM --> SERV: Return Patient
deactivate DOM

SERV -> REPO : Save updated Patient
activate REPO

REPO -> BDD : Save Entity
activate BDD

BDD --> REPO : Confirm Save
deactivate BDD

REPO --> SERV : Return Success
deactivate REPO

SERV -> DOM : Create PatientDTO
activate DOM

DOM --> SERV : Return Updated DTO
deactivate DOM

SERV --> CTRL : Return Updated DTO
deactivate SERV

<-- CTRL  : Return Updated DTO
deactivate CTRL


@enduml