@startuml 5.1.4
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "PatientController" as CTRL <<component>>
participant "PatientService" as SERV <<component>>
participant "PatientRepository" as REPO <<component>>


-> CTRL: getEditForm(ID)
activate CTRL
CTRL -> SERV: getInfo(ID)
activate SERV
SERV -> REPO: get(ID)
activate REPO
REPO --> SERV: Patient
deactivate REPO
SERV --> CTRL: Patient
deactivate SERV
<-- CTRL : PatientDto
deactivate CTRL
 -> CTRL: updatePatient(Full Name, Phone, Email, MedicalConditions, AppointmentHistory)
activate CTRL
CTRL -> SERV: updatePatient(Full Name, Phone, Email, MedicalConditions, AppointmentHistory)
activate SERV
SERV -> REPO: update(Patient)
activate REPO
REPO --> SERV: success
deactivate REPO
SERV --> CTRL: success
deactivate SERV
<-- CTRL  : success



@enduml