@startuml 5.1.4
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Patient" as AD
participant "Frontend" as FE <<component>>
participant "PatientController" as CTRL <<component>>
participant "PatientService" as SERV <<component>>
participant "PatientRepository" as REPO <<component>>

activate AD
AD -> FE: access page
activate FE
FE -> CTRL: getEditForm(ID)
activate CTRL
CTRL -> SERV: getInfo(ID)
activate SERV
SERV -> REPO: get(ID)
activate REPO
REPO --> SERV: Patient
deactivate REPO
SERV --> CTRL: Patient
deactivate SERV
CTRL --> FE: Patient
deactivate CTRL
FE --> AD: provide edit form
deactivate FE
AD -> FE : edit info of item
activate FE
FE -> CTRL: updatePatient(Phone, Email, MedicalConditions)
activate CTRL
CTRL -> SERV: updatePatient(...)
activate SERV
SERV -> REPO: update(item)
activate REPO
REPO --> SERV: success
deactivate REPO
SERV --> CTRL: success
deactivate SERV
CTRL --> FE: success
deactivate CTRL
FE --> AD : success and data

deactivate FE

deactivate AD



@enduml