@startuml 5.1.1
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "User" as AD
participant "SAaRM System" as SYS <<system>>

activate AD
AD -> SYS: access password recovery page
activate SYS
SYS --> AD : password recovery data input
deactivate SYS
AD -> SYS : email for recovery
activate SYS
SYS --> AD : success sending recovery email
deactivate SYS
AD -> SYS: access email link
activate SYS
SYS --> AD : new password data input
deactivate SYS
AD -> SYS : new password
activate SYS
SYS --> AD : success of update

deactivate SYS

deactivate AD



@enduml