@startuml 5.1.1
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Controller" as CTRL <<component>>
participant "Service" as SERV <<component>>



-> CTRL : sendRecoveryEmail(email)
activate CTRL
CTRL -> SERV: sendRecoveryEmail(email)
activate SERV
CTRL <-- SERV: success
deactivate SERV
<-- CTRL: success
deactivate CTRL


@enduml