@startuml 5.1.4
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "WebAplication" as FE <<component>>
participant "Service" as SERV <<component>>

 -> FE: access page
activate FE

FE -> SERV : getAllOperationTypes()
activate SERV


SERV -> : getOperationTypes()



SERV <-- : OperationTypesDTOList


SERV --> FE : OperationTypesDTOList
deactivate SERV

<-- FE : list of OperationTypes

deactivate FE




@enduml