@startuml 5.1.1
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "WebAplication" as FE <<component>>
participant "HTML+CSS" as HT <<component>>
participant "component" as CM <<component>>
participant "Service" as SERV <<component>>


activate FE
-> FE: access page

FE -> HT : onClick()
activate HT


HT -> CM : onLogin(loginObj)

activate CM

CM -> SERV : postLogin(loginObj)

 activate SERV

  SERV -> : Login Post Request

 SERV <-- : Success and Token to login

SERV --> CM : Success


deactivate SERV

CM --> HT : Success
deactivate CM



HT --> FE : Success
deactivate HT

<--- FE : success and access to their funtionalities.

deactivate FE





@enduml