@startuml 5.1.1
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Admin" as AD
participant "SAaRM System" as SYS <<system>>

activate AD
AD -> SYS: access page
activate SYS
SYS --> AD : data input
deactivate SYS
AD -> SYS : info to login(username, password)
activate SYS
SYS --> AD : success and access to their funtionalities.

deactivate SYS

deactivate AD



@enduml