@startuml 5.1.1
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Admin" as AD
participant "Frontend" as FE <<component>>
participant "DM Backend" as BE <<component>>



activate AD
AD -> FE: access page
activate FE
FE -> BE: getCreateForm()
activate BE
BE --> FE: form
deactivate BE
FE --> AD : data input
deactivate FE
AD -> FE : info to login(username, password)
activate FE
FE -> BE : login(username, password)
activate BE
BE --> FE: success
deactivate BE
FE --> AD : success and access to their funtionalities.
deactivate FE
deactivate AD


@enduml