@startuml 5.1.3
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Patient" as AD
participant "SAaRM System" as SYS <<system>>

activate AD
AD -> SYS : Register with external IAM credentials
activate SYS
SYS --> AD : success and data

deactivate SYS

deactivate AD



@enduml