@startuml 5.1.3
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Frontend" as FE <<component>>
participant "DM Backend" as BE <<component>>




-> FE : Register with external IAM credentials
activate FE
FE -> BE : Register with external IAM credentials
activate BE
BE --> FE: success
deactivate BE
<-- FE   : success and data


@enduml