@startuml 5.1.1
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "WebAplication" as FE <<component>>
participant "Service" as SERV <<component>>


activate FE
-> FE: access page

FE -> SERV : postLogin(loginObj)

 activate SERV

  SERV -> : Login Post Request

 SERV <-- : Success and Token to login



SERV --> FE : Success

deactivate SERV

<--- FE : success and access to their funtionalities.

deactivate FE





@enduml