@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
'skinparam shadowing false


'title Use Case Diagram Example

left to right direction

actor "Admin" as ADM
actor "Backoffice User" as BOU
actor "Staff" as STF
actor "Doctor" as DOC
actor "Patient" as PAT
actor "Nurse" as NU


usecase "UC1 - I want to register new backoffice users " as UC1
usecase "UC2 - I want to reset my password" as UC2
usecase "UC3 - I want to register for the healthcare application " as UC3
usecase "UC4 - I want to update my user profile" as UC4
usecase "UC5 - I want to delete my account and all associated data" as UC5
usecase "UC6 - I want to log in to the system using my credentials" as UC6
usecase "UC7 - I want to log in to the healthcare system using my external IAM credentials" as UC7
usecase "UC8 - I want to create a new patient profile" as UC8
usecase "UC9 - I want to edit an existing patient profile" as UC9
usecase "UC10 - I want to delete a patient profile" as UC10
usecase "UC11 - I want to list/search patient profiles by different attributes" as UC11
usecase "UC12 - I want to create a new staff profile" as UC12
usecase "UC13 - I want to edit a staff’s profile " as UC13
usecase "UC14 - I want to deactivate a staff profile" as UC14
usecase "UC15 - I want to list/search staff profiles" as UC15
usecase "UC16 - I want to request an operation" as UC16
usecase "UC17 - I want to update an operation requisition" as UC17
usecase "UC18 - I want to remove an operation requisition" as UC18
usecase "UC19 - I want to list/search operation requisitions" as UC19
usecase "UC20 - I want to add new types of operations" as UC20
usecase "UC21 - I want to edit existing operation types" as UC21
usecase "UC22 - I want to remove obsolete or no longer performed operation types" as UC22
usecase "UC23 - I want to list/search operation types" as UC23



ADM --> UC1
BOU --> UC2
PAT --> UC3
PAT --> UC4
PAT --> UC5
BOU --> UC6
PAT --> UC7
ADM --> UC8
ADM --> UC9
ADM --> UC10
ADM --> UC11
ADM --> UC12
ADM --> UC13
ADM --> UC14
ADM --> UC15
DOC --> UC16
DOC --> UC17
DOC --> UC18
DOC --> UC19
ADM --> UC20
ADM --> UC21
ADM --> UC22
ADM --> UC23



@enduml