@startuml 5.1.1
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "PatientController" as CTRL <<component>>
participant "AuthorizationService" as ASERV <<component>>
participant "PatientService" as SERV <<component>>
participant "LogService" as LSERV <<component>>
'participant "GmailService" as GSERV <<component>>
participant "Patient" as DOM <<component>>
participant "PatientRepository" as REPO <<component>>
participant "LogRepository" as LREPO <<component>>



-> CTRL: create(CreatingPatientDto dto)
'fullName,email, phone, gender, dateOfBirth, userEmail
activate CTRL
CTRL -> ASERV: ValidateUserRole(Request.Headers["Authorization"].ToString(), new List<string> {Role.ADMIN, Role.PATIENT}).Result
activate ASERV
ASERV -> CTRL : true
deactivate ASERV
CTRL -> SERV: AddAsync(CreatingPatientDto dto)
activate SERV
SERV -> DOM**: create()
SERV -> REPO: AddAsync(Patient)
activate REPO
REPO --> SERV: sucess
deactivate REPO
SERV --> CTRL: result
deactivate SERV
CTRL -> LSERV: LogAsync("Patient", "Created", result.Id, JsonConvert.SerializeObject(result))
activate LSERV
LSERV -> LREPO : AddAsync(logEntry)
activate LREPO
deactivate LREPO
deactivate LSERV
<-- CTRL: result
deactivate CTRL




@enduml