@startuml 5.1.7
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Controller" as CTRL <<component>>
participant "Service" as SERV <<component>>
participant "Repository" as REPO <<component>>

' -> CTRL: getCreateForm()
'activate CTRL
'<-- CTRL  : form
'deactivate CTRL

-> CTRL: Register Get Request
activate CTRL
CTRL -> SERV: Call GetPatientByEmailAsync method
activate SERV

SERV -> REPO: Get Patient through email
activate REPO

REPO --> SERV: Return null
deactivate REPO

SERV --> CTRL: Return null
deactivate SERV


CTRL -> SERV: Call SendEmailAsync method


<-- CTRL  : Success
deactivate CTRL




@enduml