@startuml 5.1.1
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Actor" as AD
participant "Frontend" as FE <<component>>
participant "DM Backend" as BE <<component>>



activate AD
AD -> FE: access page
activate FE
FE -> BE: getCreateForm()
activate BE
BE --> FE: form
deactivate BE
FE --> AD : data input
deactivate FE
AD -> FE : info to create item
activate FE
FE -> BE : createItem()
activate BE
BE --> FE: success
deactivate BE
FE --> AD : success and data
deactivate FE
deactivate AD


@enduml