@startuml 5.1.3
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Frontend" as FE <<component>>
participant "DM Backend" as BE <<component>>



 -> FE: access page
activate FE
FE -> BE: getCreateForm()
activate BE
BE --> FE: form
deactivate BE
<-- FE   : data input
deactivate FE
-> FE : info to create Patient Profile(fullName,email, phone, gender, dateOfBirth,userEmail)
activate FE
FE -> BE : createPatientProfile(fullName,email, phone, gender, dateOfBirth,userEmail)
activate BE
BE --> FE: success
deactivate BE
<-- FE   : success and data


@enduml