@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "WebAplication" as FE <<component>>
participant "HTML+CSS" as HT <<component>>
participant "component" as CM <<component>>
participant "Service" as SERV <<component>>

 -> FE: access page
activate FE

FE -> HT : onClick()
activate HT
HT -> CM : getAllStaffProfiles()
activate CM

CM -> SERV : getAllStaffProfiles(params)
activate SERV


SERV -> : getAll(params)



SERV <-- : MedicalConditionDTOList


SERV --> CM : MedicalConditionDTOList
deactivate SERV
CM --> HT : MedicalConditionDTOList
deactivate CM

HT --> FE : MedicalConditionDTOList
deactivate HT

<-- FE : list of Medical Conditions

deactivate FE




@enduml