@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Frontend" as FE <<component>>
participant "DM Backend" as BE <<component>>

 -> FE: access page
activate FE
FE -> BE: getAllergies()
activate BE
BE --> FE: AllergiesDTOList
deactivate BE
<-- FE : list of Allergies

deactivate FE



@enduml