@startuml 5.1.8
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Frontend" as FE <<component>>
participant "DM Backend" as BE <<component>>



 -> FE: access page
activate FE
FE -> BE: getCreateForm()
activate BE
BE --> FE: form
deactivate BE
<-- FE   : data input
deactivate FE
-> FE : info to create Operation Type(Name, duration, RequiredStaff)
activate FE
FE -> BE : createOperationType(Name, duration, RequiredStaff)
activate BE
BE --> FE: success
deactivate BE

<-- FE   : success and data


@enduml