@startuml 5.1.20
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Controller" as CTRL <<component>>
participant "Service" as SERV <<component>>
participant "Domain" as DOM <<component>>
participant "Repository" as REPO <<component>>
participant "MySql DB" as BDD <<component>>

-> CTRL: Submit Operation Type Post Type
activate CTRL

CTRL -> SERV: Call AddAsync method
activate SERV

SERV -> DOM: Create OperationType through CreatingOperationTypeDTO
activate DOM

DOM --> SERV: Return OperationType
deactivate DOM

SERV -> REPO : Save new Operation Type
activate REPO

REPO -> BDD : Save Entity
activate BDD

BDD --> REPO : Confirm Save
deactivate BDD

REPO --> SERV : Return Success
deactivate REPO

SERV -> DOM : Create OperationTypeDTO
activate DOM

DOM --> SERV : Return DTO
deactivate DOM

SERV --> CTRL : Return DTO
deactivate SERV

<-- CTRL  : Return DTO

@enduml