@startuml 5.1.8
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Frontend" as FE <<component>>
participant "DM Backend" as BE <<component>>



 -> FE: access page
activate FE
FE -> BE: getUpdateForm()
activate BE
BE --> FE: form
deactivate BE
<-- FE   : data input
deactivate FE
-> FE : info to update Appointment(SurgeryRoom, RequiredStaff, StartTime)
activate FE
FE -> BE : updateAppointment(SurgeryRoom, RequiredStaff, StartTime)
activate BE
BE --> FE: success
deactivate BE

<-- FE   : success and data


@enduml