@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "WebAplication" as FE <<component>>
participant "HTML+CSS" as HT <<component>>
participant "component" as CM <<component>>
participant "Service" as SERV <<component>>

 -> FE: access page
activate FE

FE -> HT : onClick()
activate HT
HT -> CM : getAllSpecializations()
activate CM

CM -> SERV : getAllSpecializations(params)
activate SERV


SERV -> : getAll(params)



SERV <-- : SpecializationsDTOList


SERV --> CM : SpecializationsDTOList
deactivate SERV
CM --> HT : SpecializationsDTOList
deactivate CM

HT --> FE : SpecializationsDTOList
deactivate HT

<-- FE : list of Specializations

deactivate FE




@enduml