@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Frontend" as FE <<component>>
participant "DM Backend" as BE <<component>>



-> FE: access page
activate FE
FE -> BE: GetAll(filters)
activate BE
BE --> FE: specializationDTOList
deactivate BE
<--FE: list of specializations
deactivate FE


@enduml