@startuml 5.1.1
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "WebApplication" as FE <<component>>
participant "Controller" as CTRL <<component>>
participant "Service" as SERV <<component>>
participant "DM Backend" as BE <<component>>


activate FE
-> FE: access page
activate CTRL

FE -> CTRL : onLogin




 SERV --> BE : Login Post Request


BE --> SERV : Success and Token to login

deactivate CTRL

<--- FE : success and access to their funtionalities.

deactivate FE





@enduml