@startuml 5.1.3
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Frontend" as FE <<component>>
participant "DM Backend" as BE <<component>>



-> FE: access page

activate FE

FE -> BE: getCreateForm()
activate BE
BE --> FE: form
deactivate BE
<--FE: data input

deactivate FE

-> FE : asks to delete account(email)
activate FE
FE -> BE: deactivatePatient(email)
activate BE
BE --> FE: message
deactivate BE
<-- FE  : message
deactivate FE

-> FE : confirmation to delete account(email)
activate FE
FE -> BE: confirmDeactivateAction(email)
activate BE
BE --> FE: success
deactivate BE
<-- FE  : success



deactivate FE




@enduml