@startuml
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "WebAplication" as FE <<component>>
participant "HTML+CSS" as HT <<component>>
participant "Component" as CM <<component>>
participant "Service" as SERV <<component>>





-> FE : Info to create Medical Condition
activate FE

FE -> HT : onClick()
activate HT

HT -> CM : onInsertMedicalCondition()
activate CM

CM -> SERV : createMedicalCondition(formData)
activate SERV

SERV -> : Create(MedicalConditionDTO dto)

 SERV <--: success and data


 SERV--> CM : success and data

deactivate  SERV

 CM --> HT : success and data
  deactivate CM
 HT --> FE : success and data

deactivate HT


<-- FE   : success and data
deactivate FE

@enduml