@startuml 6.2.6
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Frontend" as FE <<component>>
participant "DM Backend" as BE <<component>>



 -> FE: access page
activate FE
FE -> BE: getCreateForm()
activate BE
BE --> FE: form
deactivate BE
<-- FE   : data input
deactivate FE
-> FE : info to create Allergy(Designation, Description)
activate FE
FE -> BE : createAllergy(allergyDTO)
activate BE
BE --> FE: success
deactivate BE

<-- FE   : success and data


@enduml