@startuml 5.1.4
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "WebAplication" as FE <<component>>
participant "Service" as SERV <<component>>



-> FE : update info of Patient
activate FE
FE -> SERV : updatePatient(email, PatientDto)
activate SERV
SERV ->: update(email, PatientDto)

SERV <-- : success

SERV --> FE : sucess

deactivate SERV

alt sensitive data
SERV <-- : message
activate SERV

SERV --> FE : message


<-- FE : message
deactivate FE

-> FE : confirmation
activate FE

FE -> SERV : confirmAction(actionId, selectedPatientEmail)

SERV --> FE : sucess

deactivate SERV
end alt

deactivate SERV
<-- FE : success

deactivate FE




@enduml