@startuml 5.1.4
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Patient" as AD
participant "SAaRM System" as SYS <<system>>

activate AD
AD -> SYS: access page
activate SYS
SYS --> AD: provide update form
deactivate SYS
AD -> SYS : update info of Patient
activate SYS

SYS --> AD : success and data

deactivate SYS

deactivate AD



@enduml