@startuml 5.1.9
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Controller" as CTRL <<component>>
participant "Service" as SERV <<component>>
participant "Repository" as REPO <<component>>


-> CTRL: Submit Patient Put Request
activate CTRL

CTRL -> SERV: Call SensativeData method
activate SERV

SERV -> REPO: Get Patient through DTO Email
activate REPO


REPO --> SERV: Return Patient
deactivate REPO
alt  if is sensitive data
SERV --> CTRL: Confirmation of sensitive data
deactivate SERV

CTRL -> SERV: Call SendConfirmationUpdateEmail method
activate SERV



SERV --> CTRL : Return Success
deactivate SERV

<-- CTRL  : Return Success
deactivate CTRL

end

@enduml
