@startuml 5.1.3
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "PatientController" as CTRL <<component>>
participant "PatientService" as SERV <<component>>
'participant "PatientProfile" as DOM <<component>>
participant "UserRepository" as UREPO <<component>>
participant "PatientRepository" as REPO <<component>>



 -> CTRL: getCreateForm()
activate CTRL
<-- CTRL  : form
deactivate CTRL

 -> CTRL: deleteAccount(email)
activate CTRL
CTRL -> SERV: deleteAccount(email)
activate SERV

SERV -> UREPO: delete(email)
activate UREPO
UREPO --> SERV: success
deactivate UREPO
SERV -> REPO: delete(email)
activate REPO
REPO --> SERV: success
deactivate REPO
SERV --> CTRL: success
deactivate SERV
<-- CTRL: success
deactivate CTRL



@enduml