@startuml 5.1.3
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Patient" as AD
participant "Frontend" as FE <<component>>
participant "PatientController" as CTRL <<component>>
participant "PatientService" as SERV <<component>>
'participant "PatientProfile" as DOM <<component>>
participant "UserRepository" as UREPO <<component>>
participant "PatientProfileRepository" as REPO <<component>>



activate AD

AD -> FE: access page

activate FE

FE -> CTRL: getCreateForm()
activate CTRL
CTRL --> FE: form
deactivate CTRL
FE --> AD: data input

deactivate FE

AD -> FE : confirmation to delete account(email)
activate FE
FE -> CTRL: deleteAccount(email)
activate CTRL
CTRL -> SERV: deleteAccount(email)
activate SERV

SERV -> UREPO: delete(email)
activate UREPO
UREPO --> SERV: success
deactivate UREPO
SERV -> REPO: delete(email)
activate REPO
REPO --> SERV: success
deactivate REPO
SERV --> CTRL: success
deactivate SERV
CTRL --> FE: success
deactivate CTRL
FE --> AD : success and data

deactivate FE

deactivate AD



@enduml