@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Frontend" as FE <<component>>
participant "DM Backend" as BE <<component>>



-> FE: access page
activate FE
FE -> BE: getStaffEditForm()
activate BE
BE --> FE: form
deactivate BE
<--FE : staff data edit input
deactivate FE
 -> FE : edit info of Staff Profile
activate FE
FE -> BE : Update(string id, StaffDto dto)
activate BE
BE --> FE: success
deactivate BE
<--FE : success of operation and edited data
deactivate FE


@enduml