@startuml 5.1.21
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Controller" as CTRL <<component>>
participant "Service" as SERV <<component>>
participant "Domain" as DOM <<component>>
participant "Repository" as REPO <<component>>
participant "MySql DB" as BDD <<component>>


-> CTRL: Submit Operation Type Put Request
activate CTRL

CTRL -> SERV: Call UpdateAsync method
activate SERV

SERV -> REPO: Get OperationType through DTO Id
activate REPO

REPO --> SERV: Return OperationType
deactivate REPO

SERV -> DOM: Update OperationType with OperationTypeDTO Info
activate DOM

DOM --> SERV: Return OperationType
deactivate DOM

SERV -> REPO : Save updated Operation Type
activate REPO

REPO -> BDD : Save Entity
activate BDD

BDD --> REPO : Confirm Save
deactivate BDD

REPO --> SERV : Return Success
deactivate REPO

SERV -> DOM : Create OperationTypeDTO
activate DOM

DOM --> SERV : Return Updated DTO
deactivate DOM

SERV --> CTRL : Return Updated DTO
deactivate SERV

<-- CTRL  : Return Updated DTO
deactivate CTRL


@enduml