@startuml 5.1.21
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Frontend" as FE <<component>>
participant "DM Backend" as BE <<component>>

-> FE: access page
activate FE
FE -> BE: getEditForm(ID)
activate BE
BE --> FE: OperationTypeDto
deactivate BE
<-- FE : provide edit form
deactivate FE
-> FE : edit info of OperationType
activate FE
FE -> BE: updateOperationType(Name, RequiredStaff, EstimatedDuration)
activate BE

BE --> FE: success
deactivate BE
<-- FE : success and data

deactivate FE




@enduml