@startuml 5.1.3
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "UserController" as CTRL <<component>>
participant "AuthorizationService" as ASERV <<component>>
participant "UserService" as SERV <<component>>
participant "LogService" as LSERV <<component>>
participant "GmailService" as GSERV <<component>>
participant "UserRepository" as REPO <<component>>
participant "LogRepository" as LREPO <<component>>





 -> CTRL: Login(LoginRequest logi)
activate CTRL
CTRL -> SERV : Login(login.Username, login.Password)
activate SERV

SERV -> REPO: GetByUsernameAsync(username)
activate REPO
REPO --> SERV: user
deactivate REPO

deactivate REPO

SERV --> CTRL: UserDto
deactivate SERV
CTRL -> ASERV: GenerateToken(UserDto)
activate ASERV
ASERV -> CTRL : token
deactivate ASERV



<-- CTRL: token
deactivate CTRL



@enduml