@startuml 5.1.6
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "BackofficeUser" as AD
participant "Frontend" as FE <<component>>
participant "DM Backend" as BE <<component>>



activate AD
AD -> FE: access page
activate FE
FE -> BE: getCreateForm()
activate BE
BE --> FE: form
deactivate BE
FE --> AD : data input
deactivate FE
deactivate AD


@enduml