@startuml 5.1.1
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Controller" as CTRL <<component>>
participant "Service" as SERV <<component>>
participant "Domain" as DOM <<component>>
participant "Repository" as REPO <<component>>
participant "MySql DB" as BDD <<component>>



 -> CTRL : Login Post Request
activate CTRL
CTRL -> SERV: Call Login method

activate SERV

SERV -> REPO: Get User through Username
activate REPO

REPO --> SERV: Return UserDTO

deactivate REPO

SERV -> DOM : CheckPassword
activate DOM
DOM --> SERV : sucess

deactivate DOM

SERV --> CTRL: Return UserDTO
deactivate SERV


CTRL -> SERV: Call GenerateToken method
activate SERV

SERV --> CTRL: Token to login
deactivate SERV


<-- CTRL  : Success and Token to login
deactivate CTRL





@enduml