@startuml 5.1.1
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "BackofficeUser" as AD
participant "Frontend" as FE <<component>>
participant "UserController" as CTRL <<component>>
participant "UserService" as SERV <<component>>
participant "User" as DOM <<component>>
participant "UserRepository" as REPO <<component>>

activate AD

AD -> FE: access page

activate FE

FE -> CTRL: getCreateForm()
activate CTRL
CTRL --> FE: form
deactivate CTRL
FE --> AD: data input

deactivate FE

AD -> FE : info to create create user(email, username, role)
activate FE
FE -> CTRL: createUser(email, username, role)
activate CTRL
CTRL -> SERV: createUser(email, username, role)
activate SERV
SERV -> DOM**: create()
SERV -> REPO: save(user)
activate REPO
REPO --> SERV: success
deactivate REPO
SERV --> CTRL: success
deactivate SERV
CTRL --> FE: success
deactivate CTRL
FE --> AD : success and data

deactivate FE

deactivate AD



@enduml