@startuml 5.1.1
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "PatientController" as CTRL <<component>>
participant "PatientService" as SERV <<component>>
participant "Patient" as DOM <<component>>
participant "PatientRepository" as REPO <<component>>


 -> CTRL: getCreateForm()
activate CTRL
<-- CTRL  : form
deactivate CTRL

-> CTRL: createPatient(fullName,email, phone, gender, dateOfBirth,(?))
activate CTRL
CTRL -> SERV: createPatient(fullName,email, phone, gender, dateOfBirth,(?))
activate SERV
SERV -> DOM**: create()
SERV -> REPO: save(Patient)
activate REPO
REPO --> SERV: success
deactivate REPO
SERV --> CTRL: success
deactivate SERV
<-- CTRL: success
deactivate CTRL




@enduml