@startuml 5.1.1
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Admin" as AD
participant "Frontend" as FE <<component>>
participant "PatientController" as CTRL <<component>>
participant "PatientService" as SERV <<component>>
participant "Patient" as DOM <<component>>
participant "PatientRepository" as REPO <<component>>

activate AD

AD -> FE: access page

activate FE

FE -> CTRL: getCreateForm()
activate CTRL
CTRL --> FE: form
deactivate CTRL
FE --> AD: data input

deactivate FE

AD -> FE : info to create Patient(fullName,email, phone, gender, dateOfBirth,(?))
activate FE
FE -> CTRL: createPatient(fullName,email, phone, gender, dateOfBirth,(?))
activate CTRL
CTRL -> SERV: createPatient(fullName,email, phone, gender, dateOfBirth,(?))
activate SERV
SERV -> DOM**: create()
SERV -> REPO: save(Patient)
activate REPO
REPO --> SERV: success
deactivate REPO
SERV --> CTRL: success
deactivate SERV
CTRL --> FE: success
deactivate CTRL
FE --> AD : success and data

deactivate FE

deactivate AD



@enduml