@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Controller" as CTRL <<component>>
participant "Service" as SERV <<component>>
participant "Repository" as REPO <<component>>
participant "Domain" as DOM <<component>>

-> CTRL: SoftDelete(id)
activate CTRL
CTRL -> SERV: InactivateAsync(id)
activate SERV
SERV -> REPO: GetByStaffIDAsync(id)
activate REPO
REPO --> SERV: staffProfile
deactivate REPO
SERV -> DOM: MarkAsInative()
activate DOM
DOM --> SERV: success
deactivate DOM
SERV --> CTRL: success
deactivate SERV
<--CTRL: success




@enduml