@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Actor" as AD
participant "Frontend" as FE <<component>>
participant "Controller" as CTRL <<component>>
participant "ItemService" as SERV <<component>>
participant "ItemRepository" as REPO <<component>>

activate AD
AD -> FE: access page
activate FE
FE -> CTRL: delete(ID)
activate CTRL
CTRL -> SERV: delete(ID)
activate SERV
SERV -> REPO: delete(ID)
activate REPO
REPO --> SERV: success
deactivate REPO
SERV --> CTRL: success
deactivate SERV
CTRL --> FE: success
deactivate CTRL
FE --> AD : success

deactivate FE

deactivate AD



@enduml