@startuml
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "WebAplication" as FE <<component>>
participant "HTML+CSS" as HT <<component>>
participant "Component" as CM <<component>>
participant "Service" as SERV <<component>>





-> FE : Info to create Staff Profile
activate FE

FE -> HT : onClick()
activate HT

HT -> CM : createStaff(formData)
activate CM

CM -> SERV : createStaff(formData)
activate SERV

SERV -> : Create Staff Profile

 SERV <--: success and data


 SERV--> CM : success and data

deactivate  SERV

 CM --> HT : success and data
  deactivate CM
 HT --> FE : success and data

deactivate HT


<-- FE   : success and data
deactivate FE

@enduml