@startuml 5.1.3
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "WebAplication" as FE <<component>>
participant "HTML+CSS" as HT <<component>>
participant "component" as CM <<component>>
participant "Service" as SERV <<component>>

-> FE : confirmation to delete profile(email)
activate FE

FE -> HT : onClick()
activate HT
HT -> CM : deactivatePatient(email)
activate CM

CM -> SERV: deactivatePatient(email)
activate SERV

 SERV -> : deleteByEmail(email)

 SERV <-- : success


 SERV --> CM : success

deactivate SERV

CM --> HT : success 
deactivate CM

HT --> FE : success
deactivate HT


<-- FE  : success 

deactivate FE




@enduml