@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Admin" as AD
participant "SAaRM System" as SYS <<system>>

activate AD
AD -> SYS: access page
activate SYS
SYS --> AD : specialization data edit input
deactivate SYS
AD -> SYS : edit info of specialization
activate SYS
SYS --> AD : success of operation and edited data

deactivate SYS

deactivate AD



@enduml