export const defaultMedicalConditions = [
  { codigo: "A04.0",descricao: "Cholera" },
  { codigo: "A08.0",descricao: "Rotavirus enteritis" },
  { codigo: "B20",descricao: "Human Immunodeficiency Virus (HIV) disease" },
  { codigo: "B50",descricao: "Plasmodium falciparum malaria" },
  { codigo: "2A20.0",descricao: "Malignant neoplasm of lung" },
  { codigo: "2F44.0",descricao: "Malignant neoplasm of the breast" },
  { codigo: "3A01.1",descricao: "Iron deficiency anemia" },
  { codigo: "4A44",descricao: "Hereditary hemochromatosis" },
  { codigo: "5A11",descricao: "Type 1 diabetes mellitus" },
  { codigo: "5B55",descricao: "Obesity" },
  { codigo: "6A80",descricao: "Major depressive disorder" },
  { codigo: "6C40",descricao: "Generalized anxiety disorder" },
  { codigo: "FB20.1",descricao: "Osteoporosis with pathological fracture" },
  { codigo: "FB81.1",descricao: "Osteoarthritis of the knee" },
  { codigo: "FB81.2",descricao: "Osteoarthritis of the hip" },
  { codigo: "FB80.1",descricao: "Rheumatoid arthritis" },
  { codigo: "FA24.0",descricao: "Fracture of femur" },
  { codigo: "FA22.0",descricao: "Fracture of radius and ulna" },
  { codigo: "FA21.0",descricao: "Dislocation of shoulder" },
  { codigo: "FB70.0",descricao: "Low back pain" }
]
