export const defaultAllergies = [
  { designacao: "Peanut Allergy", descricao: "" },
  { designacao: "Shellfish Allergy", descricao: "e.g., shrimp, lobster" },
  { designacao: "Milk Allergy", descricao: "Dairy products" },
  { designacao: "Egg Allergy", descricao: "" },
  { designacao: "Tree Nut Allergy", descricao: "e.g., almonds, walnuts" },
  { designacao: "Wheat Allergy", descricao: "" },
  { designacao: "Penicillin Allergy", descricao: "" },
  { designacao: "Sulfa Drugs Allergy", descricao: "e.g., sulfamethoxazole" },
  { designacao: "Aspirin Allergy", descricao: "" },
  { designacao: "Local Anesthetics Allergy", descricao: "e.g., Lidocaine" },
  { designacao: "Pollen Allergy", descricao: "e.g., grass, ragweed" },
  { designacao: "Dust Mite Allergy", descricao: "" },
  { designacao: "Mold Allergy", descricao: "" },
  { designacao: "Cat Dander Allergy", descricao: "" },
  { designacao: "Dog Dander Allergy", descricao: "" },
  { designacao: "Latex Allergy", descricao: "" },
  { designacao: "Nickel Allergy", descricao: "common in jewelry or metal objects" },
  { designacao: "Bee Sting Allergy", descricao: "" },
  { designacao: "Fire Ant Sting Allergy", descricao: "" },
  { designacao: "Perfume Allergy", descricao: "fragrance sensitivity" },
];
