@startuml


interface "User Interface Admin" as UIA
interface "User Interface Patients" as UIP
interface "User Interface Doutors" as UID
interface "API" as API
interface "AutheNAPI" as AutheNAPI

UID -- [Project]
UIP -- [Project]
UIA -- [Project]
[Project] -- API

[Project] - AutheNAPI

@enduml



