@startuml 5.1.4
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Admin" as AD
participant "SAaRM System" as SYS <<system>>

activate AD
AD -> SYS: access page
activate SYS
SYS --> AD: provide filters form
deactivate SYS
AD -> SYS : filters
activate SYS

SYS --> AD : success and data

deactivate SYS

deactivate AD



@enduml