@startuml 5.1.4
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Frontend" as FE <<component>>
participant "DM Backend" as BE <<component>>

 -> FE: access page
activate FE
FE -> BE: getOperationTypes()
activate BE
BE --> FE: OperationTypesDTOList
deactivate BE
<-- FE : list of OperationTypes

deactivate FE




@enduml