@startuml 5.1.4
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Frontend" as FE <<component>>
participant "DM Backend" as BE <<component>>

-> FE: access page
activate FE
FE -> BE: getEditForm(ID)
activate BE
BE --> FE: AdminDto
deactivate BE
<-- FE : provide filters form
deactivate FE
-> FE : filters
activate FE
FE -> BE: GetAllFiltered(name, specialization, status)
activate BE

BE --> FE: operationTypes
deactivate BE
<-- FE : success and operationTypes

deactivate FE




@enduml