@startuml 5.1.4
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Frontend" as FE <<component>>
participant "DM Backend" as BE <<component>>

-> FE: access page
activate FE
FE -> BE: getEditForm(ID)
activate BE
BE --> FE: operationRequestDto
deactivate BE
<-- FE : provide edit form
deactivate FE
-> FE : edit info of Request Operation
activate FE
FE -> BE: updateOperationRequest(deadline, priority)
activate BE

BE --> FE: success
deactivate BE
<-- FE : success and data

deactivate FE




@enduml