@startuml 5.1.4
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "WebAplication" as FE <<component>>
participant "HTML+CSS" as HT <<component>>
participant "Component" as CM <<component>>
participant "Service" as SERV <<component>>



-> FE : Edit info of Operation Request
activate FE

 FE -> HT : onClick()
 activate HT

 HT -> CM : onUpdateRequest(requestData)
activate CM
CM -> SERV : updateOperationRequests(requestData)
activate SERV
SERV ->: Update Operation Request


SERV <-- : success

SERV --> CM : success

deactivate SERV
CM --> HT: success

deactivate CM

HT --> FE : success
deactivate HT

<-- FE : success


deactivate FE




@enduml