@startuml 5.1.9
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Frontend" as FE <<component>>
participant "DM Backend" as BE <<component>>

-> FE: access page
activate FE
FE -> BE: getEditForm(email)
activate BE
BE --> FE: AllergyDto
deactivate BE
<-- FE : provide edit form
deactivate FE
-> FE : edit info of Allergy
activate FE
FE -> BE: updateAllergy(designation, AllergyDTO)
activate BE

BE --> FE: success
deactivate BE
<-- FE : success and data

deactivate FE




@enduml