@startuml 5.1.8
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Frontend" as FE <<component>>
participant "DM Backend" as BE <<component>>



 -> FE: access page
activate FE
FE -> BE: getCreateForm()
activate BE
BE --> FE: form
deactivate BE
<-- FE   : data input
deactivate FE
-> FE : info to create Operation Request(OperationTypeName, PatientEmail, Priority, Deadline)
activate FE
FE -> BE : createOperationRequest(OperationTypeName, PatientEmail, Priority, Deadline)
activate BE
BE --> FE: success
deactivate BE

<-- FE   : success and data


@enduml