@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Frontend" as FE <<component>>
participant "DM Backend" as BE <<component>>

 -> FE: access page
activate FE
FE -> BE: getPatients()
activate BE
BE --> FE: PatientsDTOList
deactivate BE
<-- FE : list of Patients

deactivate FE



@enduml