@startuml 5.1.17
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "OperationRequestController" as CTRL <<component>>
participant "AuthenticationService" as Auth <<component>>

participant "OperationRequestService" as SERV <<component>>

participant "IStaffRepository" as StaffRep <<component>>

participant "OperationRequestRepository" as REPO <<component>>
participant "OperationRequest" as DOM <<component>>
participant "IUnitOfWork" as unit <<component>>
participant "OperationRequestDto" as dto <<component>>

participant "LogService" as Log <<component>>
participant "LogEntry" as LogEntry <<component>>
participant "ILogRepository" as LogRep <<component>>

-> CTRL: Update(id, operationRequestDto)
activate CTRL

CTRL -> Auth: ValidateUserRole(authorizationHeader, Role)
activate Auth

Auth --> CTRL : true
deactivate Auth

CTRL -> Auth: GetUserEmail(authorizationHeader)
activate Auth

Auth --> CTRL: doctorEmail
deactivate Auth

CTRL -> SERV: UpdateAsync(operationRequestDto, doctorEmail)
activate SERV

SERV -> SERV : CheckDoctorAsync(doctorEmail)
activate SERV

SERV -> StaffRep : GetByUsernameAsync(email)
activate StaffRep

StaffRep --> SERV : doctor
deactivate StaffRep

SERV --> SERV : doctor
deactivate SERV

SERV -> SERV : CheckDate(dto.Deadline)

SERV -> SERV : CheckPriority(dto.Priority)

SERV -> REPO : GetByIdAsync(dto.Id)
activate REPO

REPO --> SERV : operationRequest
deactivate REPO

SERV -> DOM : ChangeDeadline(dto.Deadline)

SERV -> DOM : ChangePriority(dto.Priority)

SERV -> unit : CommitAsync()

SERV -> dto: create(id, patId, docId, opTypeId, deadline, priority)
activate dto
dto --> SERV: operationRequestDto
deactivate dto
SERV --> CTRL: operationRequestDto
deactivate SERV

CTRL --> Log : LogAsync(entity, action, operationRequestDto.Id, changes)
activate Log

Log -> LogEntry : create(entity, action, operationRequestDto.Id, changes)
activate LogEntry

LogEntry --> Log : logEntry
deactivate LogEntry

Log -> LogRep : AddAsync(logEntry)

Log --> CTRL
deactivate Log

<-- CTRL: operationRequestDto
deactivate CTRL

@enduml