@startuml 5.1.4
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Doctor" as AD
participant "SAaRM System" as SYS <<system>>

activate AD
AD -> SYS: access page
activate SYS
SYS --> AD: provide edit form
deactivate SYS
AD -> SYS : edit info of Operation Request
activate SYS

SYS --> AD : success and data

deactivate SYS

deactivate AD



@enduml