@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Doctor" as AD
participant "SAaRM System" as SYS <<system>>

activate AD
AD -> SYS: access page
activate SYS
SYS --> AD : list of OperationRequests

deactivate SYS

deactivate AD



@enduml