@startuml 5.1.19
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Controller" as CTRL <<component>>
participant "Service" as SERV <<component>>
participant "Domain" as DOM <<component>>
participant "Repository" as REPO <<component>>
participant "MySql DB" as BDD <<component>>

-> CTRL: Submit Operation Request List Request
activate CTRL

CTRL -> SERV: Call GetALLFilteredAsync method
activate SERV

SERV -> REPO: Get All OperationRequests
activate REPO

REPO --> SERV: Operation Request List
deactivate REPO

SERV -> SERV: Filter List
activate SERV

SERV --> SERV: Filtered List
deactivate SERV

SERV -> DOM : Converts List into OperationRequestDTO List
activate DOM

DOM --> SERV : Return DTO List
deactivate DOM

SERV --> CTRL : Return DTO List
deactivate SERV

<-- CTRL  : Return DTO List
deactivate CTRL

@enduml