@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Frontend" as FE <<component>>
participant "DM Backend" as BE <<component>>

 -> FE: access page
activate FE
FE -> BE: getOperationRequests()
activate BE
BE --> FE: OperationRequestsDTOList
deactivate BE
<-- FE : list of OperationRequestsDTOList

deactivate FE



@enduml