@startuml 5.1.18
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Controller" as CTRL <<component>>
participant "Service" as SERV <<component>>
participant "Domain" as DOM <<component>>
participant "Repository" as REPO <<component>>
participant "MySql DB" as BDD <<component>>

-> CTRL: Submit Operation Request Delete Request
activate CTRL

CTRL -> SERV: Call DeleteAsync method
activate SERV

SERV -> REPO: Get OperationRequest through Id
activate REPO

REPO --> SERV: Operation Request
deactivate REPO

SERV -> REPO : Remove Operation Request
activate REPO

REPO -> BDD : Remove Entity
activate BDD

BDD --> REPO : Confirm Removal
deactivate BDD

REPO --> SERV : Return Success
deactivate REPO

SERV -> DOM : Create OperationRequestDTO
activate DOM

DOM --> SERV : Return DTO
deactivate DOM

SERV --> CTRL : Return DTO
deactivate SERV

<-- CTRL  : Return DTO
deactivate CTRL

@enduml