@startuml 5.1.1
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Admin" as AD
participant "Frontend" as FE <<component>>
participant "DM Backend" as BE <<component>>



activate AD
AD -> FE: access page
activate FE
FE -> BE: getCreateForm()
activate BE
BE --> FE: form
deactivate BE
FE --> AD : data input
deactivate FE
AD -> FE : info to create info to create user (email, username, role)
activate FE
FE -> BE : createUser(email, username, role)
BE --> FE: success
deactivate BE
FE --> AD : success and data
deactivate FE
deactivate AD


@enduml