@startuml 5.1.1
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "OperationRequestController" as CTRL <<component>>
participant "AuthenticationService" as Auth <<component>>

participant "OperationRequestService" as SERV <<component>>

participant "IStaffRepository" as StaffRep <<component>>
participant "IOperationTypeRepository" as OpTyRep <<component>>
participant "IPatientRepository" as PatRep <<component>>

participant "OperationRequest" as DOM <<component>>
participant "OperationRequestRepository" as REPO <<component>>
participant "OperationRequestDto" as dto <<component>>

''participant "LogService" as Log <<component>>
''participant "LogEntry" as LogEntry <<component>>
''participant "ILogRepository" as LogRep <<component>>


-> CTRL: Create(operationRequestDto)
activate CTRL

CTRL -> Auth: GetUserEmail(authorizationHeader)
activate Auth

Auth --> CTRL: doctorEmail
deactivate Auth

CTRL -> SERV: AddAsync(operationRequestDto, doctorEmail)
activate SERV

SERV -> StaffRep : GetByUsernameAsync(doctorEmail)
activate StaffRep

StaffRep --> SERV : doctor
deactivate StaffRep

SERV -> OpTyRep : GetByIdAsync(operationTypeId)
activate OpTyRep

OpTyRep --> SERV : operationType
deactivate OpTyRep

SERV -> PatRep : GetByIdAsync(patientId)
activate PatRep

PatRep --> SERV : patient
deactivate PatRep

SERV -> DOM: create(dto.MedicalRecordNumber, doctor.Id, dto.OperationTypeId, dto.Deadline, dto.Priority)
activate DOM

DOM --> SERV : operationRequest
deactivate DOM

SERV -> REPO: AddAsync(OperationRequest)

SERV -> dto: create(id, patId, docId, opTypeId, deadline, priority)
activate dto
dto --> SERV: operationRequestDto
deactivate dto
SERV --> CTRL: operationRequestDto
deactivate SERV

''CTRL --> Log : LogAsync(entity, action, operationRequestDto.Id, changes)
''activate Log

''Log -> LogEntry : create(entity, action, entityId, changes)
''activate LogEntry

''LogEntry --> Log : logEntry
''deactivate LogEntry

''Log -> LogRep : AddAsync(logEntry)

''Log --> CTRL
''deactivate Log

<-- CTRL: success
deactivate CTRL

@enduml