@startuml 5.1.1
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Doctor" as AD
participant "SARM System" as SYS <<system>>

activate AD
AD -> SYS: access page
activate SYS
SYS --> AD : data input
deactivate SYS
AD -> SYS : search allergie/medical condition in medical record
activate SYS
SYS --> AD : success and view allergie/medical conditions.

deactivate SYS

deactivate AD



@enduml