@startuml 7.2.6
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "WebAplication" as FE <<component>>
participant "HTML+CSS" as HT <<component>>
participant "component" as CM <<component>>



activate FE
-> FE: access page

FE -> HT : onClick()
activate HT


HT -> CM : onSearchAllergie(allergieDescription)

activate CM

CM --> CM




CM --> HT : Success and view allergies
deactivate CM



HT --> FE : Success and view allergies
deactivate HT

<--- FE : success and view medical record updated

deactivate FE





@enduml