@startuml 5.1.1
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "Frontend" as FE <<component>>
participant "DM Backend2" as BE <<component>>



 -> FE: access page
activate FE
FE -> BE: getCreateForm()
activate BE
BE --> FE: form
deactivate BE
--> FE : data input
deactivate FE
 -> FE : view medical record(patientEmail)
activate FE
FE -> BE : viewMedicalRecord(patientEmail)
activate BE
BE --> FE: success
deactivate BE
--> FE: success and view medical record.
deactivate FE



@enduml