@startuml 7.2.6
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "WebAplication" as FE <<component>>
participant "HTML+CSS" as HT <<component>>
participant "component" as CM <<component>>
participant "Service" as SERV <<component>>


activate FE
-> FE: access page

FE -> HT : onClick()
activate HT


HT -> CM : onViewedicalRecord(patientEmail)

activate CM

CM -> SERV : postViewMedicalRecord(patientEmail)

 activate SERV

   SERV -> : Patient Post Request

  SERV <-- : Success and Patient

  note right: this a reference to GetPatientByEmail (already implemented)

  SERV -> : Medical Record Get Request

 SERV <-- : Success and Medical Record

SERV --> CM : Success and Medical Record


deactivate SERV

CM --> HT : Success and Medical Record
deactivate CM



HT --> FE : Success and Medical Record
deactivate HT

<--- FE : success and view medical record view

deactivate FE





@enduml