@startuml 5.1.4
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant "WebAplication" as FE <<component>>
participant "HTML+CSS" as HT <<component>>
participant "component" as CM <<component>>
participant "Service" as SERV <<component>>

 -> FE: access page
activate FE

FE -> HT : onClick()
activate HT
HT -> CM : getAllOperationRequests()
activate CM

CM -> SERV : getAllOperationRequests()
activate SERV


SERV -> : get Operations Requests



SERV <-- : OperationRequestDTO


SERV --> CM : OperationRequestDTO
deactivate SERV
CM --> HT : OperationRequestDTO
deactivate CM

HT --> FE : OperationRequestDTO
deactivate HT

<-- FE : list of Operation Requests

deactivate FE




@enduml